### ISSUE TITLE
usePopcorn styling issue

### ISSUE THREAD

**Issue by codedhola** [jonasschmedtmann/ultimate-react-course#15]
The usePorn has unneccessary scroll features that makes the design look ugly from start

**Comment by fayzullayev** [comment]
What OS do you use? I had the same issue on Windows Chrome. But Mac's Chrome it works well.

**Comment by codedhola** [comment]
I thinks it’s the final css design he included in the starter file, which has the y scroll effect, was able to fix it though, I use Ubuntu though

**Comment by WaqarAhmad321** [comment]
Press F3 in vs code, search overflow in CSS file and make its value from y-scroll to auto. It will fix the issue.
