### ISSUE TITLE
the entire bookings folder is messed in The Wild oasis

### ISSUE THREAD

**Issue by yohannes-mesay** [jonasschmedtmann/ultimate-react-course#78]
It is not aligning properly with the video sequence and contains unused functions from the source file which should appear after some sections of the video, (for example check this folder -final-4-after-advanced-patterns)

**Comment by joiscode121** [comment]
Thanks for the alert, I will be on the lookout when I get to that section!

**Comment by yohannes-mesay** [comment]
the case is that the booking part should be copied from the bookings folder in the starter template and this works for other parts too, thanks
